# **NumPy Introduction**

# **What is NumPy?**
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

# **Why Use NumPy?**
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

# **Why is NumPy Faster Than Lists?**
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.



# **Which Language is NumPy written in?**
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.



# **Where is the NumPy Codebase?**
The source code for NumPy is located at this github repository `https://github.com/numpy/numpy`

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [2]:
type(arr)

numpy.ndarray

In [5]:
# NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.
import numpy as np

a = np.array(42)   # 0 dimention array
b = np.array([1, 2, 3, 4, 5])  # 1 dimention array
c = np.array([[1, 2, 3],
              [4, 5, 6]]
             )                      # 2 dimention array
d = np.array([[[1, 2, 3], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 6]]])  # multi- dimention array

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


**Array creation with default value:**

np.zeros(shape) ; where shape is 1,2,3,4,5.....

In [11]:
import numpy as np
zeros_array = np.zeros(3)   #For zero array  where zero is the default value
print(zeros_array)
ones_array = np.ones(3)     # For one array where one is the default value
print(ones_array)
full_array = np.full((2,2),7) # Full(shape,value) function
print(full_array)

[0. 0. 0.]
[1. 1. 1.]
[[7 7]
 [7 7]]


# **Creating sequence of numbers**

np.arange(start,stop,step)

In [13]:
import numpy as np
seq_array = np.arange(10)
print(seq_array)
s_arr = np.arange(10,20,2)
print(s_arr)

[0 1 2 3 4 5 6 7 8 9]
[10 12 14 16 18]


In [14]:
# Creating identity matrix
#
#
#
#

import numpy as np
identity_matrix = np.eye(3)
print(identity_matrix)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
####  Use of shape  to know the details shape of this matrix it is usefull for big dataset to know her size

import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [16]:
####    Use size for know the size of matrix or say that how many elements are there in this matrix
#
#
#
#

import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.size)

8


In [21]:
##  type change in array using astype() for some time need to work with different type data

import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)
newarr = arr.astype('S') # S means string
print(newarr)
print(newarr.dtype)
newarr1 = arr.astype(float)
print(newarr1)
print(newarr1.dtype)
newarr2 = arr.astype(bool)
print(newarr2)
print(newarr2.dtype)
newarr3 = arr.astype(complex)
print(newarr3)
print(newarr3.dtype)
newarr4 = arr.astype(str)  #str means string
print(newarr4)
print(newarr4.dtype)

int64
[b'1' b'2' b'3' b'4']
|S21
[1. 2. 3. 4.]
float64
[ True  True  True  True]
bool
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex128
['1' '2' '3' '4']
<U21


# **Math Function**

In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Basic arithmetic operations
print("Addition:", np.add(arr, 10))
print("Subtraction:", np.subtract(arr, 2))
print("Multiplication:", np.multiply(arr, 5))
print("Division:", np.divide(arr, 2))
print("Power:", np.power(arr, 2))

# Trigonometric functions
print("Sine:", np.sin(arr))
print("Cosine:", np.cos(arr))
print("Tangent:", np.tan(arr))

# Exponential and logarithmic functions
print("Exponential:", np.exp(arr))
print("Natural logarithm:", np.log(arr))
print("Base-10 logarithm:", np.log10(arr))

# Square root
print("Square root:", np.sqrt(arr))

# Absolute value
print("Absolute value:", np.abs([-1, -2, 3, 4]))

# Rounding
print("Round:", np.round([1.2, 2.5, 3.8]))
print("Floor:", np.floor([1.2, 2.5, 3.8]))
print("Ceil:", np.ceil([1.2, 2.5, 3.8]))

Addition: [11 12 13 14 15 16 17 18]
Subtraction: [-1  0  1  2  3  4  5  6]
Multiplication: [ 5 10 15 20 25 30 35 40]
Division: [0.5 1.  1.5 2.  2.5 3.  3.5 4. ]
Power: [ 1  4  9 16 25 36 49 64]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825]
Cosine: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003]
Tangent: [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146]
Exponential: [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03]
Natural logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154]
Base-10 logarithm: [0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999]
Square root: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712]
Absolute value: [1 2 3 4]
R

# **Aggregation Function**

In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Sum of array elements
print("Sum:", np.sum(arr))

# Minimum element in array
print("Minimum:", np.min(arr))

# Maximum element in array
print("Maximum:", np.max(arr))

# Mean of array elements
print("Mean:", np.mean(arr))

# Median of array elements
print("Median:", np.median(arr))

# Standard deviation of array elements
print("Standard Deviation:", np.std(arr))

# Variance of array elements
print("Variance:", np.var(arr))

# Product of array elements
print("Product:", np.prod(arr))

# Cumulative sum of array elements
print("Cumulative Sum:", np.cumsum(arr))

# Cumulative product of array elements
print("Cumulative Product:", np.cumprod(arr))

# Percentile
print("75th Percentile:", np.percentile(arr, 75))

Sum: 36
Minimum: 1
Maximum: 8
Mean: 4.5
Median: 4.5
Standard Deviation: 2.29128784747792
Variance: 5.25
Product: 40320
Cumulative Sum: [ 1  3  6 10 15 21 28 36]
Cumulative Product: [    1     2     6    24   120   720  5040 40320]
75th Percentile: 6.25
