# **Slicing**

array[start:stop:step]

In [1]:
import numpy as np
# Example of slicing a list
my_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# Slice from index 2 to 7 (exclusive)
slice1 = my_list[2:7]
print(f"Slice 1 (2:7): {slice1}")

# Slice from the beginning to index 5 (exclusive)
slice2 = my_list[:5]
print(f"Slice 2 (:5): {slice2}")

# Slice from index 3 to the end
slice3 = my_list[3:]
print(f"Slice 3 (3:): {slice3}")

# Slice the entire list
slice4 = my_list[:]
print(f"Slice 4 (:): {slice4}")

# Slice with a step of 2
slice5 = my_list[::2]
print(f"Slice 5 (::2): {slice5}")

# Slice from index 1 to 8 with a step of 3
slice6 = my_list[1:8:3]
print(f"Slice 6 (1:8:3): {slice6}")

# Reverse the list using slicing
slice7 = my_list[::-1]
print(f"Slice 7 (::-1): {slice7}")

# Example of slicing a string
my_string = "Hello, World!"

# Slice from index 7 to the end
string_slice1 = my_string[7:]
print(f"String Slice 1 (7:): {string_slice1}")

# Slice from the beginning to index 5
string_slice2 = my_string[:5]
print(f"String Slice 2 (:5): {string_slice2}")

# Slice with a step of 2
string_slice3 = my_string[::2]
print(f"String Slice 3 (::2): {string_slice3}")

Slice 1 (2:7): [2, 3, 4, 5, 6]
Slice 2 (:5): [0, 1, 2, 3, 4]
Slice 3 (3:): [3, 4, 5, 6, 7, 8, 9]
Slice 4 (:): [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Slice 5 (::2): [0, 2, 4, 6, 8]
Slice 6 (1:8:3): [1, 4, 7]
Slice 7 (::-1): [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
String Slice 1 (7:): World!
String Slice 2 (:5): Hello
String Slice 3 (::2): Hlo ol!


# **Fancy indexing**

Selecting multiple elements at once

In [2]:
import numpy as np

# Create a NumPy array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Fancy indexing with a list of indices
indices = [0, 2, 4, 6, 8]
fancy_slice1 = arr[indices]
print(f"Fancy slice 1 (indices {indices}): {fancy_slice1}")

# Fancy indexing with a boolean array
boolean_indices = arr > 5
fancy_slice2 = arr[boolean_indices]
print(f"Fancy slice 2 (elements > 5): {fancy_slice2}")

# Fancy indexing with a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = [0, 1, 2]
col_indices = [1, 2, 0]
fancy_slice3 = arr_2d[row_indices, col_indices]
print(f"Fancy slice 3 (elements at specific row/column pairs): {fancy_slice3}")

Fancy slice 1 (indices [0, 2, 4, 6, 8]): [0 2 4 6 8]
Fancy slice 2 (elements > 5): [6 7 8 9]
Fancy slice 3 (elements at specific row/column pairs): [2 6 7]


# **Reshaping and manipulating in arrays**

In [3]:
import numpy as np

# Create a NumPy array
arr = np.arange(12)
print(f"Original array: {arr}")

# Reshape the array
reshaped_arr = arr.reshape(3, 4)
print(f"Reshaped array (3x4): {reshaped_arr}")

# Flatten the array
flattened_arr = reshaped_arr.flatten()
print(f"Flattened array: {flattened_arr}")

# Transpose the array
transposed_arr = reshaped_arr.T
print(f"Transposed array: {transposed_arr}")

# Concatenate arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))
print(f"Concatenated array: {concatenated_arr}")

# Split array
split_arr = np.split(concatenated_arr, 2)
print(f"Split array: {split_arr}")

# Add elements
arr_with_added_elements = np.append(arr1, [7, 8])
print(f"Array with added elements: {arr_with_added_elements}")

# Delete elements
arr_with_deleted_elements = np.delete(arr_with_added_elements, [3, 4])
print(f"Array with deleted elements: {arr_with_deleted_elements}")

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array (3x4): [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Concatenated array: [1 2 3 4 5 6]
Split array: [array([1, 2, 3]), array([4, 5, 6])]
Array with added elements: [1 2 3 7 8]
Array with deleted elements: [1 2 3]


# **Ravel & Flatten**
 `ravel()` and `flatten() `methods in NumPy for converting a multi-dimensional array into a one-dimensional array.

`ravel()` returns a view of the original array if possible, meaning changes to the raveled array might affect the original array.


`flatten()` always returns a copy of the original array, so changes to the flattened array will not affect the original array.

In [4]:
import numpy as np

# Create a NumPy array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Original 2D array:\n{arr_2d}")

# Using ravel() - returns a view if possible, otherwise a copy
raveled_arr = arr_2d.ravel()
print(f"Array after ravel(): {raveled_arr}")

# Using flatten() - always returns a copy
flattened_arr = arr_2d.flatten()
print(f"Array after flatten(): {flattened_arr}")

# Demonstrate the difference between ravel() and flatten()
# Modifying the raveled array might affect the original array (if it's a view)
raveled_arr[0] = 100
print(f"Original 2D array after modifying raveled array:\n{arr_2d}")

# Modifying the flattened array does not affect the original array (it's a copy)
flattened_arr[0] = 200
print(f"Original 2D array after modifying flattened array:\n{arr_2d}")
print(f"Modified flattened array: {flattened_arr}")

Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array after ravel(): [1 2 3 4 5 6 7 8 9]
Array after flatten(): [1 2 3 4 5 6 7 8 9]
Original 2D array after modifying raveled array:
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]
Original 2D array after modifying flattened array:
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]
Modified flattened array: [200   2   3   4   5   6   7   8   9]


# **Array Modification**

In [7]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])
print(f"Original array: {arr}")

# Append elements
arr_append = np.append(arr, [6, 7])
print(f"Array after appending elements: {arr_append}")

# Insert elements
arr_insert = np.insert(arr, 2, [10, 11]) # Insert [10, 11] before index 2 ------>>>>>> array[array,index,value,axis=0(Rowise)/1(Columnise)]
print(f"Array after inserting elements: {arr_insert}")

# Delete elements
arr_delete = np.delete(arr, [0, 4]) # Delete elements at index 0 and 4
print(f"Array after deleting elements: {arr_delete}")

# Modify element at a specific index
arr_modify = arr.copy() # Create a copy to avoid modifying the original
arr_modify[2] = 100
print(f"Array after modifying element at index 2: {arr_modify}")

# Modify elements based on a condition
arr_conditional_modify = arr.copy()
arr_conditional_modify[arr_conditional_modify > 3] = 99
print(f"Array after conditional modification: {arr_conditional_modify}")


#### arr.append -->> Add element in last of an array
#### arr.insert -->> Add element in an specific position of an array

Original array: [1 2 3 4 5]
Array after appending elements: [1 2 3 4 5 6 7]
Array after inserting elements: [ 1  2 10 11  3  4  5]
Array after deleting elements: [2 3 4]
Array after modifying element at index 2: [  1   2 100   4   5]
Array after conditional modification: [ 1  2  3 99 99]


`vstack` and ` hstack `

In [8]:
import numpy as np

# Create two NumPy arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stack arrays vertically
vstack_arr = np.vstack((arr1, arr2))
print(f"Vertical stacking (vstack):\n{vstack_arr}")

# Create two more NumPy arrays
arr3 = np.array([[7, 8], [9, 10]])
arr4 = np.array([[11, 12], [13, 14]])

# Stack arrays horizontally
hstack_arr = np.hstack((arr3, arr4))
print(f"Horizontal stacking (hstack):\n{hstack_arr}")

Vertical stacking (vstack):
[[1 2 3]
 [4 5 6]]
Horizontal stacking (hstack):
[[ 7  8 11 12]
 [ 9 10 13 14]]


In [9]:
import numpy as np

# Create a NumPy array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"Original array: {arr}")

# Split the array into 5 equal parts
split_arr1 = np.split(arr, 5)
print(f"Array split into 5 equal parts: {split_arr1}")

# Split the array at specific indices
split_arr2 = np.split(arr, [2, 5, 8]) # Split before index 2, 5, and 8
print(f"Array split at indices [2, 5, 8]: {split_arr2}")

# Create a 2D NumPy array
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(f"Original 2D array:\n{arr_2d}")

# Split the 2D array horizontally (along columns)
split_arr_2d_h = np.hsplit(arr_2d, 2) # Split into 2 equal columns
print(f"2D array split horizontally:\n{split_arr_2d_h}")

# Split the 2D array vertically (along rows)
split_arr_2d_v = np.vsplit(arr_2d, 3) # Split into 3 equal rows
print(f"2D array split vertically:\n{split_arr_2d_v}")

Original array: [0 1 2 3 4 5 6 7 8 9]
Array split into 5 equal parts: [array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]
Array split at indices [2, 5, 8]: [array([0, 1]), array([2, 3, 4]), array([5, 6, 7]), array([8, 9])]
Original 2D array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2D array split horizontally:
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]
2D array split vertically:
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]
